spring.application.name=Movienatic

spring.datasource.url=jdbc:postgresql://localhost:5432/movienaticdb
spring.datasource.username=adminatic
spring.datasource.password=movienatic2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Utilizamos hibernate.ddl-auto=update para que Hibernate actualice automáticamente el esquema de la base de datos, es decir "sincroniza pero sin destruir nada"
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.image-base-url=https://image.tmdb.org/t/p/w500
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiOTkxYTYzYmRhZjM1NTEwZDg0NjE4MzYzNmYyNDVlOCIsIm5iZiI6MTc5MDE4NjI4MS41NjQ5OTk4LCJzdWIiOiI2YWI0MTMyOWQyYTk5NzRkOTk4NjVkY2QiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.O1vcTdqIi_82vqv9lziFkJGEGxO70tjmMI5wzAyX1k4