spring.application.name=Movienatic

spring.datasource.url=jdbc:postgresql://localhost:5432/movienaticdb
spring.datasource.username=adminatic
spring.datasource.password=movienatic2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true